### ISSUE TITLE
Missing Content on Shelves or the Shelf itself

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/Community-App#23]
- [ ] [Community Core Values](https://app.contentful.com/spaces/943xvw9uyovc/entries/4lzjJU7CxGaqQiw8SUK2OY)
- [ ] Men's Summit shelf doesn't show up.
- [ ] Young Adult series not showing

**Comment by jlandon** [comment]
@frizman21

1. The `publishDate` field on all the Community Core Values and Young Adult posts is empty, but that field is currently required in the app. I can change that if you don't want that to be a requirement.
2. The app currently hides shelves that have 0 posts, so that's why Men's Summit isn't showing up. I'll fix that in the next build
